version: "3.9"
services:
  app:
    container_name: cxr-ui
    build:
      context: frontend/
    ports:
      - "5000:80"
    depends_on:
      - "stage1"
      - "stage2"
      - "stage3"
    networks:
      - cxr
  stage1:
    container_name: cxr-stage1
    build:
      context: backend/stage1
    ports:
      - "5001:5000"
    networks:
      - cxr
  stage2:
    container_name: cxr-stage2
    build:
      context: backend/stage2
    ports:
      - "5002:5000"
    networks:
      - cxr
  stage3:
    container_name: cxr-stage3
    build:
      context: backend/stage3
    ports:
      - "5003:5000"
    networks:
      - cxr

networks:
  cxr: