# This is a workflow to build and deploy Chest X-ray UI
name: Frontend deployment

on:
  workflow_dispatch:

  push:
    branches:
    - master
    paths:
    - 'frontend/**'

jobs:
  
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup node v12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      
      # Speed up following runs by caching node modules
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      
      - name: Install packages
        run: |
          npm install
          npm install -g @angular/cli
        working-directory: ./frontend
        
      - name: Build
        run: ng build --prod
        working-directory: ./frontend
      
      - name: Configure Backend URL
        run: |
          JSON_CONFIG='{"backend":{"stage1_url":"%s","stage2_url":"http://127.0.0.1:5001/"}}\n'
          printf "$JSON_CONFIG" "$BACKEND_URL" >> ./frontend/dist/chest-ui/assets/config/config.json
        shell: bash
        env:
          BACKEND_URL: ${{secrets.AWS_S3_BUCKET}}
          
        
        
          
      - name: Deploy
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          # for information about setting environment variables, check following links
          # https://github.com/marketplace/actions/s3-sync
          # https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-central-1'
          SOURCE_DIR: './frontend/dist/chest-ui'
