# This is a workflow to build and deploy Chest X-ray UI
name: Frontend deployment

on:
  push:
    branches: [ master ]

jobs:
  
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Setup node v12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Install packages
        run: |
          npm install
          npm install -g @angular/cli
        working-directory: ./frontend
      - name: Build dist
        run: ng build --prod
        working-directory: ./frontend
          
#  deploy:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@master
#      - uses: jakejarvis/s3-sync-action@master
#        with:
#          args: --acl public-read --follow-symlinks --delete
#        env:
#          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          AWS_REGION: 'eu-central-1'    # optional: defaults to us-east-1
#          SOURCE_DIR: 'public'          # optional: defaults to entire repository
#
